### ISSUE TITLE
dependabot/renovate

### ISSUE THREAD

**Issue by modem7** [galaxyproject/wheelforge#18]
Heya,

Thanks so much for this repo, it's definitely helped me out!

I'm wondering if there's a way to split the meta.yaml into two separate files. A meta and a requirements.txt.

This would allow services like dependabot to submit pull requests automatically.

**Comment by nsoranzo** [comment]
@modem7 Thanks for the appreciation, good to know this is being used outside of its original purpose!

I think this should be possible by using a `pyproject.toml` file for each recipe (combining also the current `env.sh` file), e.g. for `python-ldap`:

```toml
[project]
dependencies = [
  "python-ldap==3.4.0",
]

[tool.cibuildwheel.linux]
before-all = "yum install -y openldap-devel"
```

and for `fcsparser`:

```toml
[project]
dependencies = [
  "fcsparser==0.2.0",
]

[tool.wheelforge]
purepy = true
```

How does that sound to you?
Although not sure when I'd have time to work on that.
